// File generated by FlutterFire CLI.
// Run: flutterfire configure
// to regenerate with your actual Firebase project credentials.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase project values.
  // Run: dart pub global activate flutterfire_cli
  //      flutterfire configure

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDs7i04k42v69t-6jwkaUgM2ZDKwPbc84',
    appId: '1:646724848403:web:9ae1f7137c736af2ebe8e6',
    messagingSenderId: '646724848403',
    projectId: 'edutech-smk-app',
    authDomain: 'edutech-smk-app.firebaseapp.com',
    storageBucket: 'edutech-smk-app.firebasestorage.app',
    measurementId: 'G-1PWF8LCJPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQH0jNdJVnxgEf3NcRPanVs5u8pRx4Alw',
    appId: '1:646724848403:android:53257f4f329d8351ebe8e6',
    messagingSenderId: '646724848403',
    projectId: 'edutech-smk-app',
    storageBucket: 'edutech-smk-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1zyhlrYmrlY1Bjai-3mjRjsc1zRCKw3Y',
    appId: '1:646724848403:ios:3b347b228cde0e8eebe8e6',
    messagingSenderId: '646724848403',
    projectId: 'edutech-smk-app',
    storageBucket: 'edutech-smk-app.firebasestorage.app',
    iosBundleId: 'com.example.edutechSmk',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.edutechSmk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );
}
